name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm run install:all
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    
    - name: Run linting (with continue-on-error)
      run: cd client && npm run lint || echo "Linting had errors but we will continue"
      continue-on-error: true
    
    - name: Build client
      run: npm run build
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        VITE_REACT_APP_API_URL: ${{ secrets.VITE_REACT_APP_API_URL || 'http://localhost:5000' }}
      
    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: client/build
        key: ${{ runner.os }}-build-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-build-

  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Restore build artifacts
      uses: actions/cache@v3
      with:
        path: client/build
        key: ${{ runner.os }}-build-${{ github.sha }}
    
    # Example deployment to Heroku
    # Uncomment and add your secrets when ready to deploy
    # - name: Deploy to Heroku
    #   uses: akhileshns/heroku-deploy@v3.12.12
    #   with:
    #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
    #     heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
    #     heroku_email: ${{ secrets.HEROKU_EMAIL }}
    #     usedocker: false
    #     env:
    #       GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    #       NODE_ENV: production
    #       VITE_REACT_APP_API_URL: ${{ secrets.VITE_REACT_APP_API_URL }} 